default:
  before_script:
    - export HTTP_PROXY="${PROXY}"
    - export HTTPS_PROXY="${PROXY}"
    - export NO_PROXY="*.myfiinet.com,*.efoxconn.com,harbor01.ces.myfiinet.com,10.62.172.124"

dev-build:
  stage: build
  tags:
    - maven
  rules:
    - if: '$CI_COMMIT_TAG =~ /^DEV-.*$/'
      when: on_success
    - when: never
  script:
    - echo "This pipeline is running for $CI_COMMIT_REF_NAME"
    - docker login harbor01.ces.myfiinet.com --username ${HARBOR_ACCOUNT} --password ${HARBOR_PWD}
    - docker compose build
    - docker compose push

dev-deploy:
  stage: deploy
  rules:
    - if: '$CI_COMMIT_TAG =~ /^DEV-.*$/'
      when: on_success
    - when: never
  before_script:
    - chmod 600 ${ODOO_AP1_PEM}
    - echo "IP:${ODOO_AP1_IP} | PEM:${ODOO_AP1_PEM}"
  script:
    - echo "Start deploy odoo external api $CI_COMMIT_TAG to dev"
    - echo "CI_COMMIT_TAG=${CI_COMMIT_TAG}" > .env
    - echo "MODE=sit" >> .env
    - ssh -i ${ODOO_AP1_PEM} -o StrictHostKeyChecking=no ${ODOO_AP1_USER}@${ODOO_AP1_IP} -- "sudo mkdir -p /opt/odoo_external_api"
    - scp -i ${ODOO_AP1_PEM} .env ${ODOO_AP1_USER}@${ODOO_AP1_IP}:/opt/odoo_external_api
    - scp -i ${ODOO_AP1_PEM} docker-compose.yml ${ODOO_AP1_USER}@${ODOO_AP1_IP}:/opt/odoo_external_api
    - ssh -i ${ODOO_AP1_PEM} -o StrictHostKeyChecking=no ${ODOO_AP1_USER}@${ODOO_AP1_IP} -- "docker login harbor01.ces.myfiinet.com --username ${HARBOR_ACCOUNT} --password ${HARBOR_PWD} && cd /opt/odoo_external_api && docker compose down && export CI_COMMIT_TAG=${CI_COMMIT_TAG} && docker compose pull && docker compose up --no-build -d"